steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'test', '--region', 'us-central1', '--entry-point', 'hello_http', '--runtime', 'python39', '--trigger-http']

options:
  logging: CLOUD_LOGGING_ONLY

