steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'test', '--region', 'us-central1', '--entry-point', 'hello_http', '--runtime', 'python39', '--trigger-http']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'test', '--region', 'us-central1', '--member=allUsers', '--role=roles/cloudfunctions.invoker']


options:
  logging: CLOUD_LOGGING_ONLY

