steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - functions
  - deploy
  - hello_http
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

